<?php
/** @var \Tmvc\Backend\Block\Backend $block */
/** @var \Tmvc\Framework\View\View $this */
?>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin - Dashboard</title>

    <!-- Bootstrap core CSS-->
    <link href="<?php echo $block->getPubUrl("sb_admin/bootstrap/css/bootstrap.min.css") ?>" rel="stylesheet">

    <!-- Custom fonts for this template-->
    <link href="<?php echo $block->getPubUrl("sb_admin/fontawesome-free/css/all.min.css") ?>" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="<?php echo $block->getPubUrl("sb_admin/datatables/dataTables.bootstrap4.css") ?>" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="<?php echo $block->getPubUrl("css/sb-admin.css") ?>" rel="stylesheet">

    <!-- Bootstrap core JavaScript-->
    <script src="<?php echo $block->getPubUrl("sb_admin/jquery/jquery.min.js") ?>"></script>
    <script src="<?php echo $block->getPubUrl("sb_admin/bootstrap/js/bootstrap.bundle.min.js") ?>"></script>

    <!-- Core plugin JavaScript-->
    <script src="<?php echo $block->getPubUrl("sb_admin/jquery-easing/jquery.easing.min.js") ?>"></script>

    <!-- Page level plugin JavaScript-->
    <script src="<?php echo $block->getPubUrl("sb_admin/chart.js/Chart.min.js") ?>"></script>
    <script src="<?php echo $block->getPubUrl("sb_admin/datatables/jquery.dataTables.js") ?>"></script>
    <script src="<?php echo $block->getPubUrl("sb_admin/datatables/dataTables.bootstrap4.js") ?>"></script>


</head>

<body id="page-top">

<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="<?php echo $block->getUrlBuilder()->getUrl('*') ?>"><?php echo $block->getAppName() ?></a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <span class="badge badge-danger">9+</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <span class="badge badge-danger">7</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user-circle fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">Settings</a>
                <a class="dropdown-item" href="#">Activity Log</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="<?php echo $block->getUrlBuilder()->getUrl('*/logout') ?>"><?php echo "Logout" ?></a>
            </div>
        </li>
    </ul>

</nav>

<div id="wrapper">

    <!-- Menu -->
    <?php echo $this->loadSection("menu", "Tmvc_Backend::backend/menu.phtml", $block) ?>

    <div id="content-wrapper">

        <div class="container-fluid">
            <!-- Breadcrumbs-->
            <?php echo $this->loadSection("breadcrumbs", "Tmvc_Backend::backend/breadcrumbs.phtml", $block) ?>
            <div class="content">
                <?php echo $block->loadSectionContent() ?>
            </div>
        </div>

    </div>
    <!-- /.content-wrapper -->

</div>
<!-- /#wrapper -->
<!-- Sticky Footer -->
<footer class="sticky-footer">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright © <?php echo $block->getAppName() ?> <?php echo date('Y') ?></span>
        </div>
    </div>
</footer>

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

</body>

</html>
