<?php
/** @var \Tmvc\Backend\Block\LoginForm $block */
?>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin - Login</title>

    <!-- Bootstrap core CSS-->
    <link href="<?php echo $block->getPubUrl("sb_admin/bootstrap/css/bootstrap.min.css") ?>" rel="stylesheet">

    <!-- Custom fonts for this template-->
    <link href="<?php echo $block->getPubUrl("sb_admin/fontawesome-free/css/all.min.css") ?>" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template-->
    <link href="<?php echo $block->getPubUrl("css/sb-admin.css") ?>" rel="stylesheet">

</head>

<body class="bg-dark">

<div class="container">
    <div class="card card-login mx-auto mt-5">
        <div class="card-header">Login</div>
        <div class="card-body">
            <form method="post" action="<?php echo $block->getPostUrl() ?>">
                <div class="form-group">
                    <div class="form-label-group">
                        <input type="text" id="inputEmail" name="username" class="form-control" placeholder="Email address" required="required" autofocus="autofocus">
                        <label for="inputEmail">Username</label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-label-group">
                        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required="required">
                        <label for="inputPassword">Password</label>
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Login</button>
            </form>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="<?php echo $block->getPubUrl("sb_admin/jquery/jquery.min.js") ?>"></script>
<script src="<?php echo $block->getPubUrl("sb_admin/bootstrap/js/bootstrap.bundle.min.js") ?>"></script>

<!-- Core plugin JavaScript-->
<script src="<?php echo $block->getPubUrl("sb_admin/jquery-easing/jquery.easing.min.js") ?>"></script>

</body>

</html>
