<?php
/** @var \Tmvc\Backend\Block\Backend $block */
?>
<link href="<?php echo $block->getPubUrl("menu/css/menu.css") ?>" rel="stylesheet">

<ul class="sidebar navbar-nav section menu">
    <?php foreach($block->getMenuSections() as $menuSection): ?>
        <?php echo $block->getSectionHtml($menuSection) ?>
    <?php endforeach; ?>
</ul>

<script type="text/javascript">
    require(['jquery', 'Tmvc_Backend/menu/js/menu'], function ($) {
        $('.section.menu').menu({
            initialState: "<?php echo $block->getSectionUrl($block->getCurrentSection()) ?>"
        });
    });
</script>
