<?php
/** @var \Tmvc\Ui\Block\Widget\Listing $block */
$data = $block->getCollection()->toArray();
?>
<table class="table" id="<?php echo $block->getWidgetId() ?>">
    <thead class="thead-light">
        <tr>
            <?php foreach ($block->getCollection()->getSelect()->getFields() as $header): ?>
                <th><?php echo $header ?></th>
            <?php endforeach; ?>
            <?php if ($block->getActions()): ?>
                <th>Actions</th>
            <?php endif; ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($data as $row): ?>
            <tr>
                <?php $row = $block->renderRow($row); ?>
                <?php foreach ($row as $cellData): ?>
                    <td><?php echo $cellData ?></td>
                <?php endforeach; ?>
                <?php if ($block->getActions()): ?>
                    <td>
                        <div class="dropdown btn-group">
                            <a class="btn btn-link dropdown-toggle" data-toggle="dropdown" href="#">
                                Action <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                            <?php foreach ($block->getActions() as $action): ?>
                                <li>
                                    <a class="btn btn-link" href="<?php echo $block->getSectionOrServiceUrl($action, $row) ?>"><?php echo $action['label'] ?></a>
                                </li>
                            <?php endforeach; ?>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">
    require(['jquery', 'datatables'], function ($) {
        $('#' + '<?php echo $block->getWidgetId() ?>').DataTable();
    })
</script>


