<?php
/** @var \Tmvc\Ui\Block\Messages\Init $block */
?>
<script type="text/javascript">
    require(['toastr'], function (Toastr) {
        Toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        };
        var messages = <?php echo $block->getMessages() ?>;
        messages.forEach(function (message) {
            Toastr[message.type](message.message);
            window.Toastr = Toastr;
        });
    });
</script>
